version: '3.8'

services:
  nats-server:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    healthcheck:
      test: ["CMD", "nats", "req", "-s", "nats://localhost:4222", "health", "check"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - nats-network

  ordermanager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NATS_URL: nats://demo.nats.io:4222
      NATS_QUEUE: my-subject
      HTTP_PORT: 8080
    networks:
      - nats-network
    depends_on:
      - nats-server

networks:
  nats-network:
    driver: bridge